/*
 * generated by Xtext
 */
package org.osate.altarica.ui.contentassist

import org.osate.altarica.ui.contentassist.AbstractAltaricaProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AltaricaProposalProvider extends AbstractAltaricaProposalProvider {
}
