/*
 * generated by Xtext
 */
package org.osate.altarica;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AltaricaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return org.osate.altarica.ui.internal.AltaricaActivator.getInstance().getInjector("org.osate.altarica.Altarica");
	}

}
