/*
 * generated by Xtext
 */
package org.osate.altarica;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AltaricaStandaloneSetup extends AltaricaStandaloneSetupGenerated{

	public static void doSetup() {
		new AltaricaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

