/*
 * generated by Xtext
 */
package org.osate.altarica;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AltaricaRuntimeModule extends org.osate.altarica.AbstractAltaricaRuntimeModule {

}
