/*
 * generated by Xtext
 */
package org.osate.altarica.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AltaricaUiModule extends org.osate.altarica.ui.AbstractAltaricaUiModule {
	public AltaricaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
