/*
 * generated by Xtext
 */
package org.osate.altarica.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.osate.altarica.services.AltaricaGrammarAccess;

@SuppressWarnings("all")
public class AltaricaSyntacticSequencer extends AbstractSyntacticSequencer {

	protected AltaricaGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Atom_LeftParenthesisKeyword_6_0_a;
	protected AbstractElementAlias match_Atom_LeftParenthesisKeyword_6_0_p;
	protected AbstractElementAlias match_Model___TransformationKeyword_1_0_IssuesKeyword_1_1_LeftCurlyBracketKeyword_1_2_RightCurlyBracketKeyword_1_4__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (AltaricaGrammarAccess) access;
		match_Atom_LeftParenthesisKeyword_6_0_a = new TokenAlias(true, true, grammarAccess.getAtomAccess().getLeftParenthesisKeyword_6_0());
		match_Atom_LeftParenthesisKeyword_6_0_p = new TokenAlias(true, false, grammarAccess.getAtomAccess().getLeftParenthesisKeyword_6_0());
		match_Model___TransformationKeyword_1_0_IssuesKeyword_1_1_LeftCurlyBracketKeyword_1_2_RightCurlyBracketKeyword_1_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getModelAccess().getTransformationKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getModelAccess().getIssuesKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getModelAccess().getLeftCurlyBracketKeyword_1_2()), new TokenAlias(false, false, grammarAccess.getModelAccess().getRightCurlyBracketKeyword_1_4()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Atom_LeftParenthesisKeyword_6_0_a.equals(syntax))
				emit_Atom_LeftParenthesisKeyword_6_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Atom_LeftParenthesisKeyword_6_0_p.equals(syntax))
				emit_Atom_LeftParenthesisKeyword_6_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Model___TransformationKeyword_1_0_IssuesKeyword_1_1_LeftCurlyBracketKeyword_1_2_RightCurlyBracketKeyword_1_4__q.equals(syntax))
				emit_Model___TransformationKeyword_1_0_IssuesKeyword_1_1_LeftCurlyBracketKeyword_1_2_RightCurlyBracketKeyword_1_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '-' expression=Atom
	 *     (rule start) (ambiguity) 'not' expression=Atom
	 *     (rule start) (ambiguity) 'switch' '{' 'default' ':' default=Expression
	 *     (rule start) (ambiguity) 'switch' '{' cases+=CaseExpression
	 *     (rule start) (ambiguity) name='Dirac'
	 *     (rule start) (ambiguity) name='constant'
	 *     (rule start) (ambiguity) name='exponential'
	 *     (rule start) (ambiguity) value='false'
	 *     (rule start) (ambiguity) value='true'
	 *     (rule start) (ambiguity) value=NUMBER
	 *     (rule start) (ambiguity) value=STRING
	 *     (rule start) (ambiguity) variable=[NamedElement|ID]
	 *     (rule start) (ambiguity) {Addition.left=}
	 *     (rule start) (ambiguity) {Equal.left=}
	 *     (rule start) (ambiguity) {LogicalAnd.left=}
	 *     (rule start) (ambiguity) {LogicalOr.left=}
	 *     (rule start) (ambiguity) {Multiplication.left=}
	 *     (rule start) (ambiguity) {NameRef.nested=}
	 */
	protected void emit_Atom_LeftParenthesisKeyword_6_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '-' expression=Atom
	 *     (rule start) (ambiguity) 'not' expression=Atom
	 *     (rule start) (ambiguity) {Addition.left=}
	 *     (rule start) (ambiguity) {Equal.left=}
	 *     (rule start) (ambiguity) {LogicalAnd.left=}
	 *     (rule start) (ambiguity) {LogicalOr.left=}
	 *     (rule start) (ambiguity) {Multiplication.left=}
	 */
	protected void emit_Atom_LeftParenthesisKeyword_6_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('transformation' 'issues' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     (rule start) (ambiguity) declarations+=AbstractDeclaration
	 */
	protected void emit_Model___TransformationKeyword_1_0_IssuesKeyword_1_1_LeftCurlyBracketKeyword_1_2_RightCurlyBracketKeyword_1_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
